site_name: Magnetismi
site_description: "Magnetism (Finnish: magnetismi) - another opinionated World Magnetic Model calculator."

theme:
  name: 'material'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false
  homepage: https://codes.dilettant.life/docs/
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/magnetismi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shage

copyright: Copyright &copy; 2022 Stefan Hagen under the MIT license

repo_name: ~/sthagen/magnetismi
repo_url: https://git.sr.ht/~sthagen/magnetismi
edit_uri: ""

plugins:
  - search
  - mkdocstrings

nav:
  - Introduction: 'index.md'
  - Install: 'install.md'
  - Usage: 'usage.md'
  - API: 'api.md'
  - Changes: 'changes.md'
  - Test Coverage: https://codes.dilettant.life/coverage/magnetismi
  - Third-Party: 'third-party/README.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: '∞'
  - mkautodoc
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:

